### ISSUE TITLE
range()

### ISSUE THREAD

**Issue by jayvdb** [adsharma/py2many#91]
For Python:
```python
def show():
	for i in range(1, 10):
		print(i)

if __name__ == '__main__':
	show()
```

Rust fails due to 31c2dc0e6 adding `.iter()`
```rust
error[E0599]: no method named `iter` found for struct `std::ops::Range<{integer}>` in the current scope
 --> range.rs:2:22
  |
2 |     for i in (1..10).iter() {
  |                      ^^^^ method not found in `std::ops::Range<{integer}>`
```

On Kotlin and Nim, `range` behaves differently, both printing up to 10 instead of 9.

```diff
- [b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9']
+ [b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9', b'10']
```

**Comment by adsharma** [comment]
https://github.com/adsharma/py2many/pull/92 is covering this

**Comment by adsharma** [comment]
coverage.py passes on all languages and covers ranges.
